from __future__ import annotations

import uuid

from sqlalchemy import Column, DateTime, String, Text, UniqueConstraint
from sqlalchemy.dialects.postgresql import JSONB, UUID
from sqlalchemy.sql import func

from database import Base


class ProactiveNotification(Base):
    """Notifications generated by proactive (push) insights."""

    __tablename__ = "proactive_notifications"
    __table_args__ = (UniqueConstraint("user_id", "source_type", "source_id", name="uq_proactive_user_source"),)

    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    user_id = Column(UUID(as_uuid=True), nullable=False, index=True)
    source_type = Column(String, nullable=False)  # filing | news | other
    source_id = Column(String, nullable=False)
    ticker = Column(String, nullable=True, index=True)
    title = Column(Text, nullable=True)
    summary = Column(Text, nullable=True)
    target_url = Column(Text, nullable=True)
    status = Column(String, nullable=False, default="unread", server_default="unread")
    metadata = Column(JSONB, nullable=True)
    created_at = Column(DateTime(timezone=True), nullable=False, server_default=func.now())


__all__ = ["ProactiveNotification"]
